### ISSUE TITLE
Raltion between 3D joint locations and MANO outputs

### ISSUE THREAD

**Issue by nitba** [hassony2/obman_train#9]
Hi @hassony2 ,
Thanks in advance,

for hand-only task, the output of MANO is ( root centered), for evaluation 3d location in hand dataset it is usually assumed that the output of network  be scale invariance and palm relative.

- I was wondering how you evaluate the output of mano branch on stereohand dataset, is possible to share that part too?

-  Mano output is center relative or root relative ?

-  is  Mano output scale invariance, if yes respect to each bone? (would you please refer me to code line?)

**Comment by hassony2** [comment]
- Mano output is root relative, in the case of StereoHands the root is the palm of the hand following the "palm" root flag set for this dataset: https://github.com/hassony2/obman_train/blob/56edbe3c4c6a08cea78d6704263f62e58cf175c2/mano_train/datautils.py#L24.  Given this flag, the network outputs a palm keypoint instead of a wrist keypoint https://github.com/hassony2/obman_train/blob/56edbe3c4c6a08cea78d6704263f62e58cf175c2/mano_train/networks/handnet.py#L265
- The root-relative centering is controlled by --center_idx, if you use `--center_idx 0` the centering joint is the palm (for stereohands) / wrist (for other datasets)
- The 3d mean end point errors and PCK is are computed at validation time here : https://github.com/hassony2/obman_train/blob/38dc8a4ef7bea1a31092e3e13509b597de25e842/traineval.py#L341
- When training on StereoHands, the model learns to adapt to StereoHands-specific bone lengths by learning to predict correct beta (shape) parameters, so the output is *not* scale invariant but actually in the correct 3D scale ratios

Hope this helps ! :)
